import {
  Baby,
  Banknote,
  Building,
  Building2,
  CircleParking,
  Coffee,
  Fuel,
  GraduationCap,
  Hospital,
  Hotel,
  Landmark,
  Map as MapIcon,
  MapPinned,
  Pill,
  School,
  ShoppingCart,
  Store,
  TrainFront,
  Utensils,
} from 'lucide-react'

export const CATEGORY_ICON_COMPONENTS = {
  mapPinned: MapPinned,
  shoppingCart: ShoppingCart,
  store: Store,
  baby: Baby,
  school: School,
  graduationCap: GraduationCap,
  circleParking: CircleParking,
  fuel: Fuel,
  trainFront: TrainFront,
  banknote: Banknote,
  landmark: Landmark,
  building2: Building2,
  building: Building,
  map: MapIcon,
  hotel: Hotel,
  coffee: Coffee,
  utensils: Utensils,
  hospital: Hospital,
  pill: Pill,
}
