import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { test } from 'node:test'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const read = (path) => readFileSync(join(root, path), 'utf8')

test('notification API and page scaffold match backend notification endpoints', () => {
  const notificationsApi = read('src/api/notifications.js')
  const notificationPage = read('src/pages/NotificationPage.jsx')
  const app = read('src/App.jsx')
  const bottomNavigation = read('src/components/BottomNavigation.jsx')
  const notificationButton = read('src/components/NotificationButton.jsx')
  const homePage = read('src/pages/HomePage.jsx')
  const mapPage = read('src/pages/Map.jsx')
  const archivePage = read('src/pages/ArchivePage.jsx')
  const myPage = read('src/pages/MyPage.jsx')

  assert.match(notificationsApi, /apiClient\.get\('\/api\/notifications'\)/)
  assert.match(notificationsApi, /apiClient\.get\('\/api\/notifications\/unread-count'\)/)
  assert.match(notificationsApi, /apiClient\.patch\(`\/api\/notifications\/\$\{pathSegment\(notificationId\)\}\/read`\)/)
  assert.match(notificationsApi, /apiClient\.patch\('\/api\/notifications\/read-all'\)/)

  assert.match(notificationPage, /fetchNotifications/)
  assert.match(notificationPage, /markNotificationAsRead/)
  assert.match(notificationPage, /markAllNotificationsAsRead/)
  assert.match(notificationPage, /displayMessage/)
  assert.match(notificationPage, /tracePreview/)
  assert.match(notificationPage, /getNotificationTitle/)
  assert.match(notificationPage, /traceId/)
  assert.match(notificationPage, /boardId/)
  assert.match(notificationPage, /navigate\(`\/board\/\$\{notification\.boardId\}\/trace\/\$\{notification\.traceId\}`\)/)
  assert.doesNotMatch(notificationPage, /관련 흔적 #/)
  assert.doesNotMatch(notificationPage, /보드 #/)
  assert.match(app, /path="\/notifications"/)
  assert.match(notificationButton, /fetchUnreadNotificationCount/)
  assert.match(notificationButton, /navigate\('\/notifications'\)/)
  assert.doesNotMatch(bottomNavigation, /path: '\/notifications'|key: 'notifications'|fetchUnreadNotificationCount/)
  assert.match(bottomNavigation, /grid-cols-5/)
  assert.match(homePage, /<NotificationButton/)
  assert.match(mapPage, /<NotificationButton/)
  assert.match(archivePage, /<NotificationButton/)
  assert.match(myPage, /<NotificationButton/)
})

test('follow API and list page scaffold match backend follow endpoints', () => {
  const followsApi = read('src/api/follows.js')
  const usersApi = read('src/api/users.js')
  const followListPage = read('src/pages/FollowListPage.jsx')
  const followButton = read('src/components/FollowButton.jsx')
  const friendSearchPage = read('src/pages/FriendSearchPage.jsx')
  const traceDetail = read('src/pages/TraceDetail.jsx')
  const traceBottomSheet = read('src/components/board/TraceBottomSheet.jsx')
  const tracePostUtils = read('src/utils/pages/tracePost.utils.js')
  const myPage = read('src/pages/MyPage.jsx')
  const app = read('src/App.jsx')

  assert.match(followsApi, /apiClient\.post\(`\/api\/users\/\$\{pathSegment\(userId\)\}\/follow`\)/)
  assert.match(followsApi, /apiClient\.delete\(`\/api\/users\/\$\{pathSegment\(userId\)\}\/follow`\)/)
  assert.match(followsApi, /apiClient\.get\(`\/api\/users\/\$\{pathSegment\(userId\)\}\/follow-status`\)/)
  assert.match(followsApi, /apiClient\.get\(`\/api\/users\/\$\{pathSegment\(userId\)\}\/followers`\)/)
  assert.match(followsApi, /apiClient\.get\(`\/api\/users\/\$\{pathSegment\(userId\)\}\/followings`\)/)
  assert.match(usersApi, /export function searchUsers\(keyword\)/)
  assert.match(usersApi, /apiClient\.get\('\/api\/user\/search'/)

  assert.match(followListPage, /fetchFollowers/)
  assert.match(followListPage, /fetchFollowings/)
  assert.match(followListPage, /fetchMyInfo/)
  assert.match(followListPage, /import FollowButton from '..\/components\/FollowButton'/)
  assert.match(followListPage, /setCurrentUserId\(myInfo\?\.userId/)
  assert.match(followListPage, /getProfileImageUrl/)
  assert.match(followListPage, /new URL\(profileImageUrl, API_BASE_URL\)/)
  assert.match(followListPage, /ArrowLeft/)
  assert.match(followListPage, /aria-label="뒤로가기"/)
  assert.match(followListPage, /navigate\(-1\)/)
  assert.match(followListPage, /String\(currentUserId\) !== String\(user\.userId\)/)
  assert.match(followListPage, /<FollowButton\s+targetUserId=\{user\.userId\}\s+currentUserId=\{currentUserId\}/)
  assert.match(followListPage, /useParams/)
  assert.match(app, /path="\/users\/:userId\/followers"/)
  assert.match(app, /path="\/users\/:userId\/followings"/)
  assert.match(app, /path="\/friends"/)
  assert.match(app, /<FriendSearchPage \/>/)

  assert.match(friendSearchPage, /searchUsers/)
  assert.match(friendSearchPage, /FollowButton/)
  assert.match(friendSearchPage, /닉네임 또는 사용자 ID/)
  assert.match(friendSearchPage, /currentUserId/)
  assert.match(friendSearchPage, /getProfileImageUrl/)
  assert.match(friendSearchPage, /navigate\(-1\)/)
  assert.match(myPage, /navigate\('\/friends'\)/)
  assert.match(myPage, /친구 찾기/)

  assert.match(followButton, /fetchFollowStatus/)
  assert.match(followButton, /followUser/)
  assert.match(followButton, /unfollowUser/)
  assert.match(followButton, /targetUserId === currentUserId/)
  assert.match(followButton, /팔로우/)
  assert.match(followButton, /팔로잉/)

  assert.match(tracePostUtils, /userId:\s*trace\.userId/)
  assert.match(traceDetail, /import FollowButton from '..\/components\/FollowButton'/)
  assert.match(traceDetail, /setMyUserId\(info\.userId/)
  assert.match(traceDetail, /String\(myUserId\) === String\(post\.userId\)/)
  assert.match(traceDetail, /myUserId && !isMyPost && post\.userId/)
  assert.match(traceDetail, /<FollowButton\s+targetUserId=\{post\.userId\}\s+currentUserId=\{myUserId\}/)
  assert.match(traceBottomSheet, /import FollowButton from '..\/FollowButton'/)
  assert.match(traceBottomSheet, /setMyUserId\(currentUserId\)/)
  assert.match(traceBottomSheet, /String\(currentUserId\) === String\(post\.userId\)/)
  assert.match(traceBottomSheet, /myUserId && !isMyPost && post\.userId/)
  assert.match(traceBottomSheet, /<FollowButton\s+targetUserId=\{post\.userId\}\s+currentUserId=\{myUserId\}/)
})
